version: 1
disable_existing_loggers: true



formatters:
    standard:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    error:
        format: "%(asctime)s %(levelname)s <PID %(process)d:%(processName)s> %(name)s.%(funcName)s(): %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: standard
        stream: ext://sys.stdout

    critical_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: CRITICAL
        formatter: standard
        filename: ../log/critical.log
        mode: w
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: error
        filename: ../log/errors.log
        mode: w
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    warn_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: WARN
        formatter: standard
        filename: ../log/warn.log
        mode: w
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: standard
        filename: ../log/info.log
        mode: w
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    debug_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: standard
        filename: ../log/debug.log
        mode: w
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

root:
    level: NOTSET
    handlers:
      - console
      - critical_file_handler
      - error_file_handler
      - warn_file_handler
      - info_file_handler
      - debug_file_handler
    propagate: yes

loggers:
    <module>:
        level: INFO
        handlers:
          - console
          - critical_file_handler
          - error_file_handler
          - warn_file_handler
          - info_file_handler
          - debug_file_handler
        propagate: no

    <module.x>:
        level: DEBUG
        handlers:
          - console
          - critical_file_handler
          - error_file_handler
          - warn_file_handler
          - info_file_handler
          - debug_file_handler
        propagate: yes
