logging:
  dir: '../log'
ibtracs:
  urls:
    wp: 'https://www.ncei.noaa.gov/data/international-best-track-archive-for-climate-stewardship-ibtracs/v04r00/access/netcdf/IBTrACS.WP.v04r00.nc'
  dirs:
    wp: '../data/ibtracs/'
  data_name_length: 22
era5:
  dirs:
    rea_pres_lvl_maj: '../data/era5/reanalysis_pressure_levels/majority/'
    rea_pres_lvl_min: '../data/era5/reanalysis_pressure_levels/minority/'
stdmet:
  urls:
    data: 'https://www.ndbc.noaa.gov/data/historical/stdmet/'
    stations: 'https://www.ndbc.noaa.gov/station_page.php'
  period_limit:
    start: 1970-02-26 20:00:00
    end: 9999-12-31 23:59:59
  retry_times: 10
  data_name_length: 16
  dirs:
    vars: '../data/ndbc/stdmet_variable/'
    stations: '../data/ndbc/stdmet_station_info/'
    data: '../data/ndbc/stdmet_data/'
  vars_path:
    all_year_station: '../data/ndbc/stdmet_variable/all_year_station.pkl'
    all_station_year: '../data/ndbc/stdmet_variable/all_station_year.pkl'
  prompt:
    info:
      download_station: |-
        Downloading Information of NDBC Standard Meteorological Data Station
      download_all_station: |-
        Downloading Information of [ALL] NDBC Standard Meteorological Data Station
      skip_download_station: |-
        Fail downloading information of stdmet station: 
      download_data: |-
        Downloading NDBC Standard Meteorological Data
      read_station: |-
        Reading stdmet station information
      read_data: |-
        Reading stdmet data
    error:
      fail_download_stdmet_station: |-
        Fail downloading infromation of cwind station: 
cwind:
  urls:
    data: 'https://www.ndbc.noaa.gov/data/historical/cwind/'
    stations: 'https://www.ndbc.noaa.gov/station_page.php'
  period_limit:
    start: 1988-08-31 23:00:00
    end: 9999-12-31 23:59:59
  retry_times: 10
  data_name_length: 16
  dirs:
    vars: '../data/ndbc/cwind_variable/'
    stations: '../data/ndbc/cwind_station_info/'
    data: '../data/ndbc/cwind_data/'
  vars_path:
    all_year_station: '../data/ndbc/cwind_variable/all_year_station.pkl'
    all_station_year: '../data/ndbc/cwind_variable/all_station_year.pkl'
  prompt:
    info:
      download_station: |-
        Downloading Information of NDBC Continuous Wind Station
      download_all_station: |-
        Downloading Information of [ALL] NDBC Continuous Wind Data Station
      skip_download_station: |-
        Fail downloading information of cwind station: 
      download_data: |-
        Downloading NDBC Continuous Wind Data
      read_station: |-
        Reading cwind station information
      read_data: |-
        Reading cwind data
    error:
      fail_download_cwind_station: |-
        Fail downloading infromation of cwind station: 
sfmr:
  urls:
    hurricane: 'https://www.aoml.noaa.gov/hrd/data_sub/hurr.html'
    prefix: 'https://www.aoml.noaa.gov/hrd/Storm_pages/'
    suffix: '/sfmr.html'
  period_limit:
    start: 1998-1-1 00:00:00
    end: 9999-12-31 23:59:59
  data_name_length: 21
  dirs:
    vars: '../data/sfmr/variable/'
    hurr: '../data/sfmr/hurr_data/'
    pickle: '../data/sfmr/sfmr_pickle/'
  table_names:
    prefix: 'sfmr_'
  vars_path:
    all_year_hurr: '../data/sfmr/variable/all_year_hurr.pkl'
  prompt:
    info:
      download_hurr: |-
        Downloading hurricane SFMR data
      read_hurr_record: |-
        Reading general record of hurricanes which have SFMR data
      read_hurr_sfmr: |-
        Reading hurricane SFMR data
ascat:
  urls: 'http://data.remss.com/ascat/metopa/bmaps_v02.1/'
  period_limit:
    start: 2007-03-01 00:00:00
    end: 9999-12-31 23:59:59
  data_name_length: 26
  missing_value: -999.0
  dirs:
    bmaps: '../data/satel/ascat_bmaps/'
    pickle: '../data/satel/ascat_pickle/'
  data_suffix: '_v02.1.gz'
  files_path:
    missing_dates: '../data/satel/ascat_missing_dates.pkl'
  prompt:
    info:
      download: |-
        Downloading ASCAT data
      read: |-
        Reading ASCAT data
qscat:
  urls: 'http://data.remss.com/qscat/bmaps_v04/'
  period_limit:
    start: 1999-07-19 00:00:00
    end: 2009-11-19 23:59:59
  data_name_length: 26
  missing_value: -999.0
  dirs:
    bmaps: '../data/satel/qscat_bmaps/'
    pickle: '../data/satel/qscat_pickle/'
  data_suffix: 'v4.gz'
  files_path:
    missing_dates: '../data/satel/qscat_missing_dates.pkl'
  prompt:
    info:
      download: |-
        Downloading QucikSCAT data
      read: |-
        Reading QuickSCAT data
wsat:
  urls: 'http://data.remss.com/windsat/bmaps_v07.0.1/'
  period_limit:
    start: 2003-02-05 00:00:00
    end: 9999-12-31 23:59:59
  data_name_length: 26
  missing_value: -999.0
  dirs:
    bmaps: '../data/satel/windsat_bmaps/'
    pickle: '../data/satel/windsat_pickle/'
  data_suffix: 'v7.0.1.gz'
  files_path:
    missing_dates: '../data/satel/wsat_missing_dates.pkl'
  prompt:
    info:
      download: |-
        Downloading Windsat data
      read: |-
        Reading Windsat data
result:
  dirs:
    fig: '../fig/'
database:
  db_api: 'mysql+mysqlconnector'
  user: 'root'
  host: 'localhost'
  port: '3306'
  db_name: 'SWFusion'
  args: 'use_pure=True'
  batch_size:
    insert: 1000
    query: 1000
workflow:
  default_region:
    min_latitude: -90.0
    max_latitude: 90.0
    min_longitude: 0.0
    max_longitude: 360.0
  prompt:
    input:
      start_date: |-
        [Input] Enter start datetime in form of
        YEAR/MONTH/DAY/HOUR/MINUTE/SECOND: 
      end_date: |-
        [Input] Enter end datetime in form of
        YEAR/MONTH/DAY/HOUR/MINUTE/SECOND: 
      db_root_password: >-
        [Input] Enter MySQL root password: 
      min_latitude: |-
        [Input] Enter MINIMAL latitude
        (negative if in southern hemisphere,
        press ENTER to input default value -90): 
      max_latitude: |-
        [Input] Enter MAXIMAL latitude
        (negative if in southern hemisphere,
        press ENTER to input default value 90): 
      min_longitude: |-
        [Input] Enter MINIMAL longitude
        (0~180 if in western hemisphere,
        180~360 if in eastern hemisphere,
        press ENTER to input default value 0): 
      max_longitude: |-
        [Input] Enter MAXIMAL longitude
        (0~180 if in western hemisphere,
        180~360 if in eastern hemisphere,
        press ENTER to input default value 360): 
    info:
      period: |-
        Inputting period
      specify_region: |-
        Specifying region
      mysql_root_passwd: |-
        Inputting database parameters
    error:
      too_early: |-
        Start datetime is too early. Must not be earlier than
      too_late: |-
        End datetime is too late. Must not be later than
      time_flow_backward: |-
        Start datetime is later than end datetime.
