logging:
  dir: '../log'
match:
  temporal_window: 360
wind_radii:
  - 34
  - 50
  - 64
hwind:
  data_link_text:
    gridded: 'GriddedData'
    shapefile: 'Shapefiles'
  table_name: 'hwind'
  url: 'https://www.rms.com/perils/hwind/legacy-archive/storms'
  data_url_prefix: 'https://www.rms.com'
  dirs:
    gridded: '../data/hwind/gridded/'
    shapefile: '../data/hwind/shapefile/'
  pickle:
    year_tc: '../data/hwind/variable/year_tc.pkl'
  basin_map:
    Atlantic Basin: 'NA'
    East Pacific Basin: 'EP'
    West Pacific Basin: 'WP'
ibtracs:
  table_name: 'ibtracs'
  urls:
    wp: 'https://www.ncei.noaa.gov/data/international-best-track-archive-for-climate-stewardship-ibtracs/v04r00/access/netcdf/IBTrACS.WP.v04r00.nc'
    since1980: 'https://www.ncei.noaa.gov/data/international-best-track-archive-for-climate-stewardship-ibtracs/v04r00/access/netcdf/IBTrACS.since1980.v04r00.nc'
  dirs: '../data/ibtracs/'
  data_name_length: 22
rss:
  subset_edge_in_degree: 20
  spatial_resolution: 0.25
  lat_grid_points_number: 720
  lon_grid_points_number: 1440
  missing_value: -999.0
era5:
  subset_edge_in_degree: 20
  spatial_resolution: 0.25
  lat_grid_points_number: 721
  lon_grid_points_number: 1440
  main_hours:
    - 0
    - 6
    - 12
    - 18
  vars:
    - 'geopotential'
    - 'relative_humidity'
    - 'temperature'
    - 'u_component_of_wind'
    - 'v_component_of_wind'
  pres_lvl:
    - '100'
    - '200'
    - '300'
    - '400'
    - '500'
    - '600'
    - '700'
    - '800'
    - '850'
    - '925'
    - '975'
    - '1000'
  dirs:
    threeD:
      major: '../data/era5/reanalysis_pressure_levels/threeD/major/'
      minor: '../data/era5/reanalysis_pressure_levels/threeD/minor/'
    surface:
      major: '../data/era5/reanalysis_pressure_levels/surface/major/'
      minor: '../data/era5/reanalysis_pressure_levels/surface/minor/'
stdmet:
  urls:
    data: 'https://www.ndbc.noaa.gov/data/historical/stdmet/'
    stations: 'https://www.ndbc.noaa.gov/station_page.php'
  period_limit:
    start: 1970-02-26 20:00:00
    end: 9999-12-31 23:59:59
  retry_times: 10
  data_name_length: 16
  dirs:
    vars: '../data/ndbc/stdmet_variable/'
    stations: '../data/ndbc/stdmet_station_info/'
    data: '../data/ndbc/stdmet_data/'
  vars_path:
    all_year_station: '../data/ndbc/stdmet_variable/all_year_station.pkl'
    all_station_year: '../data/ndbc/stdmet_variable/all_station_year.pkl'
  prompt:
    info:
      download_station: |-
        Downloading Information of NDBC Standard Meteorological Data Station
      download_all_station: |-
        Downloading Information of [ALL] NDBC Standard Meteorological Data Station
      skip_download_station: |-
        Fail downloading information of stdmet station: 
      download_data: |-
        Downloading NDBC Standard Meteorological Data
      read_station: |-
        Reading stdmet station information
      read_data: |-
        Reading stdmet data
    error:
      fail_download_stdmet_station: |-
        Fail downloading infromation of cwind station: 
cwind:
  urls:
    data: 'https://www.ndbc.noaa.gov/data/historical/cwind/'
    stations: 'https://www.ndbc.noaa.gov/station_page.php'
  period_limit:
    start: 1988-08-31 23:00:00
    end: 9999-12-31 23:59:59
  retry_times: 10
  data_name_length: 16
  dirs:
    vars: '../data/ndbc/cwind_variable/'
    stations: '../data/ndbc/cwind_station_info/'
    data: '../data/ndbc/cwind_data/'
  vars_path:
    all_year_station: '../data/ndbc/cwind_variable/all_year_station.pkl'
    all_station_year: '../data/ndbc/cwind_variable/all_station_year.pkl'
  prompt:
    info:
      download_station: |-
        Downloading Information of NDBC Continuous Wind Station
      download_all_station: |-
        Downloading Information of [ALL] NDBC Continuous Wind Data Station
      skip_download_station: |-
        Fail downloading information of cwind station: 
      download_data: |-
        Downloading NDBC Continuous Wind Data
      read_station: |-
        Reading cwind station information
      read_data: |-
        Reading cwind data
    error:
      fail_download_cwind_station: |-
        Fail downloading infromation of cwind station: 
sfmr:
  urls:
    hurricane: 'https://www.aoml.noaa.gov/hrd/data_sub/hurr.html'
    prefix: 'https://www.aoml.noaa.gov/hrd/Storm_pages/'
    suffix: '/sfmr.html'
  period_limit:
    start: 1998-1-1 00:00:00
    end: 9999-12-31 23:59:59
  data_name_length: 21
  dirs:
    vars: '../data/sfmr/variable/'
    hurr: '../data/sfmr/hurr_data/'
    pickle: '../data/sfmr/sfmr_pickle/'
  table_names:
    prefix: 'sfmr_'
  vars_path:
    all_year_hurr: '../data/sfmr/variable/all_year_hurr.pkl'
  prompt:
    info:
      download_hurr: |-
        Downloading hurricane SFMR data
      read_hurr_record: |-
        Reading general record of hurricanes which have SFMR data
      read_hurr_sfmr: |-
        Reading hurricane SFMR data
amsr2:
  urls: 'http://data.remss.com/amsr2/bmaps_v08/'
  period_limit:
    start: 2012-07-02 00:00:00
    end: 9999-12-31 23:59:59
  data_name_length: 20
  missing_value: -999.0
  dirs:
    bmaps: '../data/satel/amsr2_bmaps/'
  data_prefix: 'f34'
  data_suffix: 'v8.gz'
  files_path:
    missing_dates: '../data/satel/amsr2_missing_dates.pkl'
ascat:
  urls: 'http://data.remss.com/ascat/metopa/bmaps_v02.1/'
  period_limit:
    start: 2007-03-01 00:00:00
    end: 9999-12-31 23:59:59
  data_name_length: 26
  missing_value: -999.0
  dirs:
    bmaps: '../data/satel/ascat_bmaps/'
  data_prefix: 'ascat'
  data_suffix: '_v02.1.gz'
  files_path:
    missing_dates: '../data/satel/ascat_missing_dates.pkl'
  prompt:
    info:
      download: |-
        Downloading ASCAT data
      read: |-
        Reading ASCAT data
qscat:
  urls: 'http://data.remss.com/qscat/bmaps_v04/'
  period_limit:
    start: 1999-07-19 00:00:00
    end: 2009-11-19 23:59:59
  data_name_length: 26
  missing_value: -999.0
  dirs:
    bmaps: '../data/satel/qscat_bmaps/'
  data_prefix: 'qscat'
  data_suffix: 'v4.gz'
  files_path:
    missing_dates: '../data/satel/qscat_missing_dates.pkl'
  prompt:
    info:
      download: |-
        Downloading QucikSCAT data
      read: |-
        Reading QuickSCAT data
wsat:
  urls: 'http://data.remss.com/windsat/bmaps_v07.0.1/'
  period_limit:
    start: 2003-02-05 00:00:00
    end: 9999-12-31 23:59:59
  data_name_length: 26
  missing_value: -999.0
  dirs:
    bmaps: '../data/satel/windsat_bmaps/'
  data_prefix: 'wsat'
  data_suffix: 'v7.0.1.gz'
  files_path:
    missing_dates: '../data/satel/wsat_missing_dates.pkl'
  prompt:
    info:
      download: |-
        Downloading Windsat data
      read: |-
        Reading Windsat data
result:
  dirs:
    fig: '../fig/'
database:
  db_api: 'mysql+mysqlconnector'
  user: 'root'
  host: 'localhost'
  port: '3306'
  db_name: 'SWFusion'
  args: 'use_pure=True'
  batch_size:
    insert: 1000
    query: 1000
workflow:
  default_region:
    min_latitude: -90.0
    max_latitude: 90.0
    min_longitude: 0.0
    max_longitude: 360.0
  prompt:
    input:
      start_date: |-
        [Input] Enter start datetime in form of
        YEAR/MONTH/DAY/HOUR/MINUTE/SECOND: 
      end_date: |-
        [Input] Enter end datetime in form of
        YEAR/MONTH/DAY/HOUR/MINUTE/SECOND: 
      db_root_password: >-
        [Input] Enter MySQL root password: 
      min_latitude: |-
        [Input] Enter MINIMAL latitude
        (negative if in southern hemisphere,
        press ENTER to input default value -90): 
      max_latitude: |-
        [Input] Enter MAXIMAL latitude
        (negative if in southern hemisphere,
        press ENTER to input default value 90): 
      min_longitude: |-
        [Input] Enter MINIMAL longitude
        (0~180 if in western hemisphere,
        180~360 if in eastern hemisphere,
        press ENTER to input default value 0): 
      max_longitude: |-
        [Input] Enter MAXIMAL longitude
        (0~180 if in western hemisphere,
        180~360 if in eastern hemisphere,
        press ENTER to input default value 360): 
    info:
      period: |-
        Inputting period
      specify_region: |-
        Specifying region
      mysql_root_passwd: |-
        Inputting database parameters
    error:
      too_early: |-
        Start datetime is too early. Must not be earlier than
      too_late: |-
        End datetime is too late. Must not be later than
      time_flow_backward: |-
        Start datetime is later than end datetime.
