urls:
  ndbc:
    cwind: 'https://www.ndbc.noaa.gov/data/historical/cwind/'
    stations: 'https://www.ndbc.noaa.gov/station_page.php'
  sfmr:
    hurricane: 'https://www.aoml.noaa.gov/hrd/data_sub/hurr.html'
    prefix: 'https://www.aoml.noaa.gov/hrd/Storm_pages/'
    suffix: '/sfmr.html'
  ascat: 'http://data.remss.com/ascat/metopa/bmaps_v02.1/'
  qscat: 'http://data.remss.com/qscat/bmaps_v04/'
  wsat: 'http://data.remss.com/windsat/bmaps_v07.0.1/'
operation_dates:
  ascat:
    start: 2007-03-01
    end: 9999-12-31
  qscat:
    start: 1999-07-19
    end: 2009-11-19
  wsat:
    start: 2003-02-05
    end: 9999-12-31
retry_times:
  ndbc: 10
data_name_length:
  ndbc: 16
  sfmr: 25
  satel: 26
default_values:
  ndbc:
    min_latitude: -90
    max_latitude: 90
    min_longitude: 0
    max_longitude: 360
missing_values:
  ascat: -999.0
  qscat: -999.0
  wsat: -999.0
dirs:
  ndbc:
    vars: '../data/ndbc/variable/'
    stations: '../data/ndbc/station_info/'
    cwind: '../data/ndbc/cwind_data/'
    pickle: '../data/ndbc/cwind_pickle/'
  sfmr:
    vars: '../data/sfmr/variable/'
    hurr: '../data/sfmr/hurr_data/'
    pickle: '../data/sfmr/sfmr_pickle/'
  ascat:
    bmaps: '../data/satel/ascat_bmaps/'
    pickle: '../data/satel/ascat_pickle/'
  qscat:
    bmaps: '../data/satel/qscat_bmaps/'
    pickle: '../data/satel/qscat_pickle/'
  wsat:
    bmaps: '../data/satel/windsat_bmaps/'
    pickle: '../data/satel/windsat_pickle/'
data_suffix:
  ascat: '_v02.1.gz'
  qscat: 'v4.gz'
  wsat: 'v7.0.1.gz'
files_path:
  ndbc:
    station_csv: '../data/ndbc/stations.csv'
  ascat:
    missing_dates: '../data/satel/ascat_missing_dates.pkl'
  qscat:
    missing_dates: '../data/satel/qscat_missing_dates.pkl'
  wsat:
    missing_dates: '../data/satel/wsat_missing_dates.pkl'
vars_path:
  ndbc:
    year_station: '../data/ndbc/variable/year_station.pkl'
    station_year: '../data/ndbc/variable/station_year.pkl'
  sfmr:
    year_hurr: '../data/sfmr/variable/year_hurr.pkl'
prompt:
  ndbc:
    input:
      year: |-

        Inputting target year(s)

        Supporting 3 input modes:

        1. Single input, e.g. "1997 1998 2000"
        2. Range input, e,g. "1997-2001 2005-2008"
        3. Hybrid input, e.g. "1997 1999-2001 2012 2003-2010"

        Input target year(s) (only press ENTER to skip): 
      station: |-

        Inputting target station(s)

        Only support single input mode, e.g. "41001 41004 lonf1"

        Input target station(s) (only press ENTER to skip): 
      min_latitude: >-
        Enter MINIMAL latitude
        (negative if in southern hemisphere,
        press ENTER to input default value -90): 
      max_latitude: >-
        Enter MAXIMAL latitude
        (negative if in southern hemisphere,
        press ENTER to input default value 90): 
      min_longitude: >-
        Enter MINIMAL longitude
        (0~180 if in western hemisphere, 180~360 if in eastern hemisphere,
        press ENTER to input default value 0): 
      max_longitude: >-
        Enter MAXIMAL longitude
        (0~180 if in western hemisphere, 180~360 if in eastern hemisphere,
        press ENTER to input default value 360): 
    info:
      dl_station: |

        Downloading Station Information

      dl_cwind: |

        Downloading Continuous Wind Data

      specify_region: |

        Specifying region with the range of latitude and longitude

    error:
      no_input: |

        At least one of year(s) and station(s) should be specified.

      no_station_info: |

        Fail downloading station's information.
  sfmr:
    input:
      hurr: |-

        Inputting target hurricane(s)

        Formats: [year_1, hurricane_name_1] [year_2, hurricane_name_2] ...

        Input target hurricane(s): 
    info:
      dl_hurr: |

        Downloading Hurricane SFMR Data

  satel:
    input:
      satel_num: |-
        1. ASCAT
        2. QucikSCAT
        3. WindSat

        Choose satellite by entering corresponding number: 
      start_date: >-
        Enter start date in form of YEAR/MONTH/DAY: 
      end_date: >-
        Enter end date in form of YEAR/MONTH/DAY: 
    info:
      choose_satel: |

        Choosing satellite
      period: |

        Inputting period
      download: |

        Downloading satellite data
    error:
      range_too_early: |-

        [Error] Start date is too early. Must not be earlier than
      range_too_late: |-

        [Error] End date is too late. Must not be later than
      date_too_early: |-
         is too early. Must not be earlier than
      date_too_late: |-
         is too late. Must not be later than
TABLES:
  cwind_stations: |-
    CREATE TABLE `ciwnd_stations` (
      `stn_no` int(6) NOT NULL AUTO_INCREMENT,
      `id` varchar(10) NOT NULL,
      `latitude` float NOT NULL,
      `longitude` float NOT NULL,
      `site_elev` float,
      `air_temp_elev` float,
      `anemometer_elev` float,
      `barometer_elev` float
      PRIMARY KEY (`stn_no`)
    ) ENGINE=InnoDB
  cwind_data: |-
    CREATE TABLE `cwind_data` (
      `cwind_no`
